### ISSUE TITLE
broken link at the repository read-me

### ISSUE THREAD

**Issue by villares** [py5coding/py5examples#3]
«**Detailed installation instructions** are available on the documentation website. There are some Special Notes for Mac Users that you should read if you use OSX.»

![image](https://user-images.githubusercontent.com/3694604/137591217-26996d08-b5b3-4241-bb14-be597a67161f.png)

**Comment by hx2A** [comment]
Thank you for noticing this problem and for the PR. It happens the [py5 repo](https://github.com/hx2A/py5) and [py5's page on pypi](https://pypi.org/project/py5/#description) had the same broken link errors. Since I am in the process of putting together the next release, it is important that I fix both before the release.

**Comment by hx2A** [comment]
I need to fix the 404 page on the documentation website. It should not show that ugly page.
